# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
# image-digest: sha256:e7349c11c387551bafa628a25e9c68e63ed49823fbb74d5cdad63a521f8703ad
name: Bambuddy (Dev2)
version: "2026.08.09-e7349c11"
slug: bambuddy_dev2
stage: experimental
description: Bambuddy is a powerful, self-hosted command center for Bambu Lab — from one A1 to a 40-printer farm. Your Printers. No Cloud. Your Rules.
url: "https://github.com/MagicMelody84/homeassistant-app-bambuddy"
arch:
  - aarch64
  - amd64
init: false
host_network: true
hassio_role: homeassistant
privileged:
  - NET_RAW
homeassistant_api: true
map:
  - addon_config:rw
  - share:rw
  - media:rw
options:
  trusted_frame_origins:
    - "http://homeassistant.local:8123"
  enable_share: false
  enable_media: false
  use_system_trust_store: false
  certfile: "custom_ca.crt"
  debug: false
schema:
  trusted_frame_origins:
    - str
  enable_share: bool
  enable_media: bool
  use_system_trust_store: bool
  certfile: str
  debug: bool
environment:
  TRUSTED_FRAME_ORIGINS: "{{trusted_frame_origins}}"
webui: http://[HOST]:[PORT:9999]
watchdog: http://[HOST]:[PORT:9999]/health
